CREATE TABLE IF NOT EXISTS players (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE COLLATE NOCASE,
  score INTEGER NOT NULL DEFAULT 0,
  last_roll_at INTEGER NOT NULL DEFAULT 0,
  token_hash TEXT NOT NULL UNIQUE
);